-- Active: 1746303585699@@172.17.0.3@3306
/*Modelagem Banco de Dados*/
/*PRIMEIRA FORMA NORMAL - MASI EXTENSA, POSSUI 3 REGRAS*/
/*
 1ª REGRA: TODO CAMPO VETORIZADO SE TORNARÁ OUTRA TABELA, MESMA NATURAEZA
 EXEMPLO.:
 
 [AMARELO, AZUL, LARANJA, VERDER] -> CORES
 [KA, FIESTA, UNO, CIVIC] -> CARROS
 [981404539, 999407140, 978653421] -> TELEFONE
 
 2ª TODO CAMPO MULVALORADO SE TORNARÁ OUTRA TABELA, MULTIVALORADO
 É QUANDO CAMPO PODE SER DIVISIVEL. NATURAEZA DIFERENTES.
 EXEMPLO.:
 [RUA, BAIRRO, CIDADE, UF] -> ENDERECO
 
 3ª TODA TABELA NECESSITA PELO MENOS UM CAMPO QUE IDENTICA
 TODO O REGISTRO COMO SENDO UNICO 
 . ISSO É O QUE CHAMAMOS DE CHAVE PRIMARIA (PRIMARY KEY)
 
 NOTA: NAO SE MODELA PRO PROCESSEDIMENTO OU NEGOCIO, PORQUE ELES
 PODEM MUDAR.*/
SHOW DATABASES;